### ISSUE TITLE
Final Fantasy 7 Naming issue. 

### ISSUE THREAD

**Issue by douglie007** [bodgit/psx#9]
Final Fantasy 7 with this memory card gave a P instead of a - in the naming. 
[MemoryCard2-1.zip](https://github.com/bodgit/psx/files/6791889/MemoryCard2-1.zip)

**Comment by bodgit** [comment]
If you rename the memory card file so it's `SLUS-00982/SLUS-00982-1.mcd` can you load the save in FF7?

**Comment by bodgit** [comment]
I've released v0.0.4 which should have this fixed. The filename is now correctly created as `SLUS-00982/SLUS-00982-1.mcd` but the save data on the memory card is left untouched and the product code is still `SLUSP00982`. Feel free to confirm that FF7 can load that save ok.

Thanks for the bug report!
